# Generated by Django 4.1.6 on 2023-06-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrahent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Operacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacja', models.CharField(max_length=32)),
                ('stawka', models.CharField(max_length=32)),
                ('typ_operacji', models.PositiveBigIntegerField(choices=[(0, 'Zwykła'), (1, 'Kooperacja')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerweb.operacje')),
            ],
        ),
        migrations.CreateModel(
            name='Oferty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uwagi', models.TextField(default='')),
                ('nr_zew', models.CharField(max_length=32)),
                ('kontrahenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerweb.kontrahent')),
            ],
        ),
        migrations.CreateModel(
            name='Indeksy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indeks', models.CharField(max_length=32)),
                ('ilosc', models.IntegerField()),
                ('czy_mat', models.PositiveBigIntegerField(choices=[(0, 'Tak'), (1, 'Nie')], default=1)),
                ('Oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerweb.oferty')),
            ],
        ),
    ]
