# Generated by Django 4.1.6 on 2023-07-03 07:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0002_oferty_data_alter_indeksy_id_alter_kontrahent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrahent',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='kontrahent',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(1, 'Nie'), (0, 'Tak')], default=1),
        ),
        migrations.AlterField(
            model_name='kontrahent',
            name='Nazwa',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(0, 'Zwykła'), (1, 'Kooperacja')], default=0),
        ),
    ]
