# Generated by Django 4.1.6 on 2023-09-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0002_remove_indeksy_oferta_indeksy_kontrahent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(1, 'w trakcie'), (2, 'opracowana'), (0, 'nowa'), (3, 'wysłana')], default=0),
        ),
    ]
