# Generated by Django 4.1.6 on 2023-07-03 07:43

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('offerweb', '0003_kontrahent_miejscowosc_kontrahent_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrahent',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(0, 'Tak'), (1, 'Nie')], default=1),
        ),
        migrations.AlterField(
            model_name='kontrahent',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+48 ', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(1, 'Kooperacja'), (0, 'Zwykła')], default=0),
        ),
    ]
