# Generated by Django 4.1.6 on 2023-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0003_alter_oferty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferty',
            name='order_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(0, 'Tak'), (1, 'Nie')], default=1),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(3, 'wysłana'), (1, 'w trakcie'), (0, 'nowa'), (2, 'opracowana')], default=0),
        ),
    ]
