# Generated by Django 4.1.6 on 2023-07-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0004_kontrahent_address_alter_indeksy_czy_mat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontrahent',
            old_name='address',
            new_name='ulica',
        ),
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(1, 'Nie'), (0, 'Tak')], default=1),
        ),
    ]
