# Generated by Django 4.1.6 on 2023-10-04 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0004_oferty_order_number_alter_indeksy_czy_mat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(1, 'Nie'), (0, 'Tak')], default=1),
        ),
        migrations.AlterField(
            model_name='indeksy',
            name='kontrahent',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offerweb.kontrahent'),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'nowa'), (3, 'wysłana'), (1, 'w trakcie'), (2, 'opracowana')], default=0),
        ),
        migrations.RemoveField(
            model_name='technologia',
            name='operacja',
        ),
        migrations.AddField(
            model_name='technologia',
            name='operacja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offerweb.operacje'),
            preserve_default=False,
        ),
    ]
