# Generated by Django 4.2.3 on 2023-07-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0006_alter_indeksy_czy_mat_alter_operacje_typ_operacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(3, 'wysłana'), (0, 'nowa'), (2, 'opracowana'), (1, 'w trakcie')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(1, 'Kooperacja'), (0, 'Zwykła')], default=0),
        ),
    ]
