# Generated by Django 4.1.6 on 2023-10-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0006_gatunek_mytechno_alter_oferty_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(2, 'opracowana'), (3, 'wysłana'), (1, 'w trakcie'), (0, 'nowa')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(1, 'Kooperacja'), (0, 'Zwykła')], default=0),
        ),
    ]
