# Generated by Django 4.1.6 on 2023-10-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0007_alter_oferty_status_alter_operacje_typ_operacji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalkulator',
            name='dlugosc',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='kalkulator',
            name='gatunek',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='offerweb.gatunek'),
        ),
        migrations.AlterField(
            model_name='kalkulator',
            name='grubosc',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='kalkulator',
            name='profil',
            field=models.PositiveBigIntegerField(choices=[('YES', 'YES'), ('NO', 'NO')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kalkulator',
            name='srednica',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='kalkulator',
            name='szerokosc',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(2, 'opracowana'), (1, 'w trakcie'), (0, 'nowa'), (3, 'wysłana')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(0, 'Zwykła'), (1, 'Kooperacja')], default=0),
        ),
    ]
