# Generated by Django 4.1.6 on 2023-07-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0007_oferty_status_alter_operacje_typ_operacji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(1, 'w trakcie'), (3, 'wysłana'), (0, 'nowa'), (2, 'opracowana')], default=0),
        ),
    ]
