# Generated by Django 4.1.6 on 2023-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0008_alter_oferty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(0, 'Zwykła'), (1, 'Kooperacja')], default=0),
        ),
    ]
