# Generated by Django 4.1.6 on 2023-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0011_alter_kalkulator_wartosc_alter_oferty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(0, 'Tak'), (1, 'Nie')], default=1),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(2, 'opracowana'), (3, 'wysłana'), (1, 'w trakcie'), (0, 'nowa')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(1, 'Kooperacja'), (0, 'Zwykła')], default=0),
        ),
    ]
