# Generated by Django 4.1.6 on 2023-07-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0011_alter_oferty_status_alter_operacje_typ_operacji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(0, 'Tak'), (1, 'Nie')], default=1),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(2, 'opracowana'), (1, 'w trakcie'), (3, 'wysłana'), (0, 'nowa')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(0, 'Zwykła'), (1, 'Kooperacja')], default=0),
        ),
    ]
