# Generated by Django 4.1.6 on 2023-11-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0012_alter_indeksy_czy_mat_alter_oferty_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalkulator',
            name='grubosc_scianki',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='kalkulator',
            name='dlugosc',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='kalkulator',
            name='waga',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='kalkulator',
            name='wartosc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(1, 'w trakcie'), (0, 'nowa'), (2, 'opracowana'), (3, 'wysłana')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(0, 'Zwykła'), (1, 'Kooperacja')], default=0),
        ),
    ]
