# Generated by Django 4.1.6 on 2023-07-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0012_alter_indeksy_czy_mat_alter_oferty_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(1, 'Nie'), (0, 'Tak')], default=1),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(3, 'wysłana'), (2, 'opracowana'), (0, 'nowa'), (1, 'w trakcie')], default=0),
        ),
    ]
