# Generated by Django 4.1.6 on 2023-07-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0013_alter_indeksy_czy_mat_alter_oferty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeksy',
            name='indeks',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'nowa'), (1, 'w trakcie'), (3, 'wysłana'), (2, 'opracowana')], default=0),
        ),
    ]
