# Generated by Django 4.1.6 on 2023-07-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0016_alter_indeksy_czy_mat_alter_indeksy_ilosc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(3, 'wysłana'), (2, 'opracowana'), (1, 'w trakcie'), (0, 'nowa')], default=0),
        ),
    ]
