# Generated by Django 4.1.6 on 2023-07-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0019_rename_oferta_indeksy_oferta_alter_oferty_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'nowa'), (1, 'w trakcie'), (3, 'wysłana'), (2, 'opracowana')], default=0),
        ),
    ]
