# Generated by Django 4.1.6 on 2023-07-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0020_alter_oferty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeksy',
            name='kontrahent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offerweb.kontrahent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(1, 'w trakcie'), (3, 'wysłana'), (2, 'opracowana'), (0, 'nowa')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(0, 'Zwykła'), (1, 'Kooperacja')], default=0),
        ),
    ]
