# Generated by Django 4.1.6 on 2023-08-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0021_indeksy_kontrahent_alter_oferty_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologia',
            name='indeks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offerweb.indeksy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(1, 'Nie'), (0, 'Tak')], default=1),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(2, 'opracowana'), (3, 'wysłana'), (1, 'w trakcie'), (0, 'nowa')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(1, 'Kooperacja'), (0, 'Zwykła')], default=0),
        ),
    ]
