# Generated by Django 4.1.6 on 2023-08-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0026_alter_indeksy_czy_mat_alter_oferty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(2, 'opracowana'), (1, 'w trakcie'), (0, 'nowa'), (3, 'wysłana')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(0, 'Zwykła'), (1, 'Kooperacja')], default=0),
        ),
    ]
