# Generated by Django 4.1.6 on 2023-08-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0028_alter_indeksy_czy_mat_alter_oferty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeksy',
            name='czy_mat',
            field=models.PositiveBigIntegerField(choices=[(1, 'Nie'), (0, 'Tak')], default=1),
        ),
        migrations.RemoveField(
            model_name='indeksy',
            name='oferta',
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(3, 'wysłana'), (0, 'nowa'), (1, 'w trakcie'), (2, 'opracowana')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(1, 'Kooperacja'), (0, 'Zwykła')], default=0),
        ),
        migrations.AddField(
            model_name='indeksy',
            name='oferta',
            field=models.ManyToManyField(blank=True, null=True, to='offerweb.oferty'),
        ),
    ]
