# Generated by Django 4.1.6 on 2023-08-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0029_alter_indeksy_czy_mat_remove_indeksy_oferta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indeksy',
            name='oferta',
        ),
        migrations.AddField(
            model_name='oferty',
            name='indeks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offerweb.indeksy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(3, 'wysłana'), (1, 'w trakcie'), (2, 'opracowana'), (0, 'nowa')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(0, 'Zwykła'), (1, 'Kooperacja')], default=0),
        ),
    ]
