# Generated by Django 4.1.6 on 2023-08-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0030_remove_indeksy_oferta_oferty_indeks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferty',
            name='indeks',
        ),
        migrations.AddField(
            model_name='indeksy',
            name='oferta',
            field=models.ManyToManyField(to='offerweb.oferty'),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(1, 'w trakcie'), (2, 'opracowana'), (0, 'nowa'), (3, 'wysłana')], default=0),
        ),
        migrations.AlterField(
            model_name='operacje',
            name='typ_operacji',
            field=models.PositiveBigIntegerField(choices=[(1, 'Kooperacja'), (0, 'Zwykła')], default=0),
        ),
    ]
