# Generated by Django 4.1.6 on 2023-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerweb', '0031_remove_oferty_indeks_indeksy_oferta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacje',
            name='tj',
        ),
        migrations.RemoveField(
            model_name='operacje',
            name='tpz',
        ),
        migrations.AddField(
            model_name='technologia',
            name='tj',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='technologia',
            name='tpz',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='indeksy',
            name='oferta',
            field=models.ManyToManyField(related_name='oferty', to='offerweb.oferty'),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'nowa'), (3, 'wysłana'), (1, 'w trakcie'), (2, 'opracowana')], default=0),
        ),
    ]
